a=input("Enter number 1:")
b=input("Enter number 2:")
print("the no is; " ,a)
print("the no is; ",b)
print("sum  no is; ",a+b)
a=int(input("Enter number 1:"))
b=int(input("Enter number 2:"))
print("the no is; " ,a)
print("the no is; ",b)
print("sum  no is; ",a+b)
